src/main/java/com/github/firmwehr/gentle/GentleCompiler.java, src/main/java/com/github/firmwehr/gentle/source/Source.java, src/main/java/com/github/firmwehr/gentle/source/SourceException.java, src/test/java/com/github/firmwehr/gentle/lexer/LexReaderTest.java, src/test/java/com/github/firmwehr/gentle/lexer/LexerTest.java, src/test/java/com/github/firmwehr/gentle/parser/ParserTest.java
We should probably have better error handling, but crashing is better than doing nothing and just assuming the input is ASCII.
=> Reject non-ASCII source strings

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
These changes remove an additional check in the input file handling that prevents `/dev/stdin` and similar files from working.
Closes #61
=> Allow special files like /dev/stdin to be used

src/main/java/com/github/firmwehr/gentle/parser/Parser.java, src/test/java/com/github/firmwehr/gentle/parser/ParserTest.java
An expression like `new int[1][2]` should be parsed as `(new int[1])[2]` instead of resulting in an error.
=> Fix parsing of NewArrayExpressions next to an ArrayAccess

src/main/java/com/github/firmwehr/gentle/lexer/Lexer.java, src/main/java/com/github/firmwehr/gentle/source/SourceSpan.java
While the logger itself does not introduce much overhead for logging calls, the formatting of elements before passing them to the logger is inefficient. By checking if the log level is enabled before formatting, this overhead can be avoided.
=> Reduce format overhead for logger

src/main/java/com/github/firmwehr/gentle/source/Source.java
EOF tokens have an offset immediately after the last character of the file, but Source would crash if the offset didn't point to a valid character. Fixed by changing how Source calculates source positions
=> Fix Source crashing on offsets past the end of the file

src/main/java/com/github/firmwehr/gentle/lexer/Lexer.java, src/main/java/com/github/firmwehr/gentle/util/string/SimpleStringTable.java, src/main/java/com/github/firmwehr/gentle/util/string/StringTable.java
This allows us to have more control over String deduplication. The current implementation is pretty much straightforward and seems to be beneficial for performance.
=> Implement own StringTable

src/main/java/com/github/firmwehr/gentle/GentleCompiler.java, src/main/java/com/github/firmwehr/gentle/lexer/StringReader.java, src/main/java/com/github/firmwehr/gentle/source/Source.java, src/main/java/com/github/firmwehr/gentle/source/SourceException.java, src/test/java/com/github/firmwehr/gentle/parser/ParserTest.java, src/test/java/com/github/firmwehr/gentle/source/SourceTest.java
by enforcing US_ASCII as charset, we can guarantee that the files we read are always in a valid format. That way, we don't need to check that manually again.
=> Only read ASCII files by default

src/main/java/com/github/firmwehr/gentle/parser/ast/expression/BinaryOperator.java
Profiling showed that the changed method has a somewhat significant overhead. Replacing the stream with the map avoids that almost fully.
=> Implement lookup table to map Operators to BinaryOperators

src/test/java/com/github/firmwehr/gentle/testutil/Equality.java, src/test/java/com/github/firmwehr/gentle/testutil/EqualityChecker.java
This allows to check records for "equality" deeply even if they have list or optionals containing records as record components
=> Handle lists and optionals when checking record equality in tests

src/main/java/com/github/firmwehr/gentle/parser/ast/statement/WhileStatement.java
`while (true);` should be printed as `while (true) { }`, just like `if (true);` is printed as `if (true) { }`
=> Fix printing of empty statements as while loop body

src/main/java/com/github/firmwehr/gentle/semantic/MethodScope.java
This fixes the following:
```java
class Foo {
public int System;
public static void main(String[] args) {
System.out.println(2); // refers to the field here!
}
}
```
Previously it interpreted this as a `System.out.println` call.
=> Let fields shadow System in static methods

src/main/java/com/github/firmwehr/gentle/parser/Parser.java, src/main/java/com/github/firmwehr/gentle/semantic/MethodScope.java, src/test/java/com/github/firmwehr/gentle/parser/ParserTestCaseProvider.java
`-3` is a negative integer literal while `-(3)` is a negated positive integer literal. This means that `-2147483648` is valid while `-(2147483648)` is invalid.
Bug discovered thanks to Group 3's test `LargeNegativeIntegerLiteral.invalid.mj`.
=> Fix parsing of negative vs negated positive integer literals

src/main/java/com/github/firmwehr/gentle/GentleCompiler.java, src/main/java/com/github/firmwehr/gentle/source/Source.java
Fixes crash when trying to format error message for a file containing only `/*`. This PR also makes mjtest fail a test if an unexpected exception occurs.
=> Fix error messages

.github/workflows/build-docker.yml, build.gradle.kts
A docker image might be helpful for our windows friends to try out the compiler in a production environment :)
You can build it using `./gradlew jibDockerBuild`.
=> Build a docker image

src/main/java/com/github/firmwehr/gentle/firm/construction/FirmGraphBuilder.java
Fixes
```java
public static void main(String[] args) {
return;
}
```
=> Fix explicit return in main

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java, src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/ConstantFolding.java
Before this patch, all nodes were assigned a `⊥` value. This is incorrect, as you can't just assume loaded values or arguments have a single value - their value might change at every load. 
* Add a mapping from node to `⊤` or `⊥`
* Move arithmetic optimizations to their own class
* Add CLI switches to disable constant folding / arithmetic optimizations
=> Fix wrong assumption in constant folding

src/main/java/com/github/firmwehr/gentle/firm/construction/FirmGraphBuilder.java, src/main/java/com/github/firmwehr/gentle/firm/construction/TypeHelper.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/ConstantFolding.java
This fixes an issue with e.g.:
```java
class Foo {
public int a;
public int b;
public void trigger() {
public Foo f = null;
f.b = 20; /* needs to be the *second* field in the struct so an offset ADD is generated */
}
}
```
=> Convert constant to correct mode in arithmetic optimization

src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/ConstantFolding.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/GraphOptimizationStep.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/Optimizer.java
With more optimizations coming, the "static optimize method" approach might be insufficient. For example, we want to re-run optimization a if optimization b changed the graph.
To do that, we apply optimizations per graph rather than applying each optimization on the whole program.
=> Make optimizations more flexible

src/main/java/com/github/firmwehr/gentle/firm/construction/FirmGraphBuilder.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/FirmGraphCleanup.java
Previously "mod" processed arguments *after* the current state of the memory chain was read, causing their changes to get lost.
=> Fix memory chain

src/main/java/com/github/firmwehr/gentle/GentleCompiler.java
Previously gentle exited with `0` if an error occurred. This hinders automated testing of compiler crashes.
=> Exit with exit code 1 on error

src/main/java/com/github/firmwehr/gentle/firm/optimization/PureFunctionOptimization.java
The old purifier assumed that loads were pure since they had no observable side effects, but with the new purifier letting gvn deduplicate and reorder pure function calls, that is no longer true since stores might have happened in-between.
=> Fix purifier

src/main/java/com/github/firmwehr/gentle/backend/ir/codegen/CodeSelection.java, src/main/java/com/github/firmwehr/gentle/backend/ir/nodes/IkeaAnd.java, src/main/java/com/github/firmwehr/gentle/backend/ir/visit/DjungelskogVisitor.java, src/main/java/com/github/firmwehr/gentle/backend/ir/visit/IkeaVisitor.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java
`(a >> n) << n` and `(a >>> n) << n` can be replaced by one `a & -(1 << n)`. If n is a constant, that means it's only one instruction instead of two.
=> Replace consecutive right shift, left shift instructions

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java, src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java, src/main/java/com/github/firmwehr/gentle/firm/construction/FirmGraphBuilder.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/ConstantFolding.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/Optimizer.java, src/main/java/com/github/firmwehr/gentle/firm/optimization/callgraph/CallGraph.java
Especially with method inlining, this might help to further reduce compilation time as we really do not need to generate code for methods which are never called (anymore).
=> Remove methods that are never called

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java, src/main/java/com/github/firmwehr/gentle/cli/CompilerArguments.java, src/main/java/com/github/firmwehr/gentle/cli/Optimizations.java
This lets you enable individual optimizations, e. g. `./run Foo.java --gvn` instead of `./run Foo.java --optimize --no-xxx --no-yyy --no-zzz ....`
=> Shorten flag names and add non-negated versions

src/main/java/com/github/firmwehr/gentle/firm/optimization/ConstantFolding.java
We use Eor for boolean negation but forgot to include it in the constant folding optimization.
=> Fix CF for Eor nodes

src/main/java/com/github/firmwehr/gentle/firm/optimization/BooleanOptimization.java
Boolean optimization would place an unconditional jump in the incorrect location, turning this
into this
but now after the fix, it does this
=> Fix unconditional jump in incorrect places
