Firmwehr/gentle

src/main/java/com/github/firmwehr/gentle/parser/ast/Type.java

Tiny PR because I just remembered this

Prevent constructing invalid types

---

src/main/java/com/github/firmwehr/gentle/GentleCompiler.java
src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java

The `runCommand` is not reachable anymore but will be in the future so I left it in.

Add parsetest flag as specified in assignment

---

src/main/java/com/github/firmwehr/gentle/parser/ExpectedToken.java
src/main/java/com/github/firmwehr/gentle/parser/Parser.java
src/main/java/com/github/firmwehr/gentle/parser/Tokens.java

This makes the parser a bit more verbose but consistent. Not sure yet whether that's good or bad.

Change expected tokens from string to enum

---

src/main/java/com/github/firmwehr/gentle/lexer/LexerException.java
src/main/java/com/github/firmwehr/gentle/output/UserOutput.java
src/main/java/com/github/firmwehr/gentle/parser/ParseException.java
src/main/java/com/github/firmwehr/gentle/semantic/SemanticException.java
src/main/java/com/github/firmwehr/gentle/source/Source.java

Color exception messages

---

src/main/java/com/github/firmwehr/gentle/parser/Parser.java
src/main/java/com/github/firmwehr/gentle/parser/ast/expression/IntegerLiteralExpression.java
src/test/java/com/github/firmwehr/gentle/parser/ParserTestCaseProvider.java
src/test/java/com/github/firmwehr/gentle/parser/prettyprint/PrettyPrinterTest.java

Fix parsing of "-1.foo()" and similar expressions

---

src/main/java/com/github/firmwehr/gentle/GentleCompiler.java
src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/cli/CommandDispatcher.java

This PR replaces the old giant iflist by a dispatcher class that takes care of running the right command when the corresponding flag is set.

Clean up main method a little

---

src/main/java/com/github/firmwehr/gentle/linking/ExternalLinker.java

According to the new update of the assignment we should place the compiled binary in the current working directory.

Place output binary in CWD

---

.github/workflows/build-docker.yml
src/main/jib/usr/bin/gentle

* Only build image for master branch
* Include simple binary in container for using container as build image

Improve docker image

---

src/main/java/com/github/firmwehr/gentle/parser/ast/expression/UnaryOperatorExpression.java

Fix pretty printing of negated (not negative) large integer literals

---

build.gradle.kts
src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java

This adds optimizations exploiting associativity and distributivity.
Please review to make sure I didn't miss any dangerous edge cases.

Add more arithmetic optimizations

---

src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java

Set firm backend back to DEBUG mode

---

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmGraphBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/ConstantFolding.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/GraphOptimizationStep.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/Optimizer.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/UnusedParameterOptimization.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/callgraph/CallGraph.java

This implements a call graph that is built with entities as nodes and calls as edges.
I implemented one "optimization" on top of it for now, it removes unused parameters from entity types and rewrites calls accordingly. I'm not sure how much improvement that actually brings, but it was easier as other optimizations on the call graph...
Further optimizations can be built on this, but I didn't want it to become another enormous PR.

Implement call graph

---

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java

Replace error prone FIRM Version field with command line switch

---

src/main/java/com/github/firmwehr/gentle/backend/ir/IkeaParentBløck.java
src/main/java/com/github/firmwehr/gentle/backend/ir/codegen/CodeSelection.java
src/main/java/com/github/firmwehr/gentle/backend/ir/codegen/RegisterTransferGraph.java
src/main/java/com/github/firmwehr/gentle/backend/ir/nodes/IkeaMovRegister.java
src/main/java/com/github/firmwehr/gentle/backend/ir/visit/DjungelskogVisitor.java
src/main/java/com/github/firmwehr/gentle/backend/ir/visit/MolkiVisitor.java

Implement register transfer graphs

---

src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/ConstantFolding.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/FirmGraphCleanup.java

Add cleanup visitor

---

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/EscapeAnalysisOptimization.java

proof is left as an exercise to the reader

Implement escape analysis

---

src/main/java/com/github/firmwehr/gentle/firm/optimization/EscapeAnalysisOptimization.java

During other interesting experiments, we discovered two cases where the escape analysis scans Phis with themselves as input over and over again.

Fix endless loops and SO in escape analysis

---

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java

This change allows to disable all optional optimizations without explicitly using their respective disable switch.

Implement -O command line switch for disabling optional optimizations

---

.github/workflows/mjtest.yml

Add compile-only flags to mjtest runs

---

src/main/java/com/github/firmwehr/gentle/backend/ir/codegen/CodeSelection.java
src/main/java/com/github/firmwehr/gentle/backend/ir/nodes/IkeaShr.java
src/main/java/com/github/firmwehr/gentle/backend/ir/nodes/IkeaShrs.java
src/main/java/com/github/firmwehr/gentle/backend/ir/visit/DjungelskogVisitor.java
src/main/java/com/github/firmwehr/gentle/backend/ir/visit/IkeaVisitor.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java
src/main/java/com/github/firmwehr/gentle/util/Maths.java

Rewrite division and modulo with constant divisor

---

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/PureFunctionOptimization.java
src/main/java/com/github/firmwehr/gentle/util/Mut.java

Seems to pass the mjtest tests. I hope I got all relevant side-effect-ful nodes.

Remove pure functions whose result is unused

---

src/main/java/com/github/firmwehr/gentle/GentleCompiler.java
src/main/java/com/github/firmwehr/gentle/backend/ir/codegen/CodeSelection.java
src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/firm/GentleBindings.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmGraphBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/ConstantFolding.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/GlobalValueNumbering.java

This change introduces a Global Value Numbering optimization stage. The stage will iteratively identify common nodes and reroute incoming edges to a predetermined member using a union find data structure.

Implement Global Value Numbering stage

---

src/main/java/com/github/firmwehr/gentle/backend/ir/codegen/CodeSelection.java
src/main/java/com/github/firmwehr/gentle/backend/ir/nodes/IkeaShl.java
src/main/java/com/github/firmwehr/gentle/backend/ir/visit/DjungelskogVisitor.java
src/main/java/com/github/firmwehr/gentle/backend/ir/visit/IkeaVisitor.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/OptimizationList.java

Rewrite multiplications with powers of two with shifts

---

src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java

trivial optimization to remove repeating negation of a value

Remove double negation

---

src/main/java/com/github/firmwehr/gentle/firm/GentleBindings.java
src/main/java/com/github/firmwehr/gentle/firm/Util.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/EscapeAnalysisOptimization.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/MethodInliningOptimization.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/UnusedParameterOptimization.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/callgraph/CallGraph.java

This implements method inlining. The current heuristics are somewhat randomly chosen, we might want to do further investigations for good thresholds here and there.

Implement method inlining

---

src/main/java/com/github/firmwehr/gentle/firm/optimization/GlobalValueNumbering.java

These changes provide an alternative fix for poor GVN performance due to excessive hash collisions, leading to catastrophic amounts of equality checks on const nodes.
Prior to this commit, nodes with no preds shared the same hash with all other nodes of the same kind, regardless of configuration. This was done with the intent to keep the code short and under the assumption that very very few nodes from the same kind, would share the same predecessors but were configured different. This turned out to be wrong for Const and Address nodes, since they don't have any predecessors.

Alternative performance fix for slow GVN without sacrificing readability

---

.idea/inspectionProfiles/Project_Default.xml
src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/cli/CommandDispatcher.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/GraphOptimizationStep.java
src/main/java/com/github/firmwehr/gentle/jfr/SelfRecording.java
src/main/java/com/github/firmwehr/gentle/lexer/Lexer.java
src/main/java/com/github/firmwehr/gentle/parser/Parser.java
src/main/java/com/github/firmwehr/gentle/semantic/SemanticAnalyzer.java

If you have any ideas for more stuff that could be relevant, let me know.
Example output rendered by IntelliJ:

Add some JFR events for basic performance inspection

---

src/main/java/com/github/firmwehr/gentle/firm/optimization/MethodInliningOptimization.java

Methods were assumed to have infinite loops too often. Also, the callee cost calculation was totally wrong...

Improve method inlining heuristics

---

src/main/java/com/github/firmwehr/gentle/GentleCompiler.java
src/main/java/com/github/firmwehr/gentle/source/Source.java

The `UTF_8`-s are probably a copy-paste error

Always read file as ASCII

---

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/cli/CompilerArguments.java
src/main/java/com/github/firmwehr/gentle/cli/Optimizations.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/TailCallOptimization.java

- Especially tail calls where the object changes. These should not be a problem, however it's better to err on the side of caution

tail call optimization

---

.github/workflows/mjtest.yml
src/main/java/com/github/firmwehr/gentle/GentleCompiler.java
src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/cli/CompilerArguments.java
src/main/java/com/github/firmwehr/gentle/cli/Optimizations.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/ReorderInputsOptimization.java

Move Const and Load to the right

---

build.gradle.kts
src/main/java/com/github/firmwehr/gentle/backend/lego/register/X86Register.java

Fix missing preview feature flag in docker image

---

src/main/java/com/github/firmwehr/gentle/cli/CommandArguments.java
src/main/java/com/github/firmwehr/gentle/cli/CompilerArguments.java
src/main/java/com/github/firmwehr/gentle/cli/Optimizations.java
src/main/java/com/github/firmwehr/gentle/firm/GentleBindings.java
src/main/java/com/github/firmwehr/gentle/firm/construction/FirmBuilder.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/ArithmeticOptimization.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/ConstantFolding.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/LoopInvariantOptimization.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/loops/BlockBackedges.java
src/main/java/com/github/firmwehr/gentle/firm/optimization/loops/LoopTree2.java

This moves loop invariant nodes above loops :)

Add loop invariant optimization
